# Scrape data from Wundergrond (this may take a few hours)
# source("london.R")
# source("nyc.R")
# source("melbourne.R")
# source("mexcity.R")
# source("moscow.R")
# source("hongkong.R")
# source("tokyo.R")
# source("rome.R")
# source("saopaulo.R")
# source("mecca.R")
# source("delhi.R")
# source("jakarta.R")
# source("puntaarenas.R")
# source("stockholm.R")
# source("capetown.R")
# source("lagos.R")
# source("novosibirsk.R")
# source("edmonton.R")
# source("lima.R")
# source("tehran.R")
# source("reykjavik.R")
# source("nairobi.R")
# source("yakutsk.R")
# source("beijing.R")

weather<-read.csv("london.csv", header=TRUE, stringsAsFactors=FALSE)
weather<-rbind(read.csv("nyc.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("melbourne.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("mexcity.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("moscow.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("hongkong.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("tokyo.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("rome.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("saopaulo.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("mecca.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("delhi.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("jakarta.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("puntaarenas.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("stockholm.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("capetown.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("lagos.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("novosibirsk.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("edmonton.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("lima.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("tehran.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("reykjavik.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("nairobi.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("yakutsk.csv", header=TRUE, stringsAsFactors=FALSE),weather)
weather<-rbind(read.csv("beijing.csv", header=TRUE, stringsAsFactors=FALSE),weather)

# There's some kind of fuckery going on with some cities. They decided that 
# instead of putting "NA" or leaving the date blank, it would be
# prudent to populate it with "-99999". Thanks a lot, jerks.

weather$Mean.TemperatureF<-as.numeric(weather$Mean.TemperatureF)
weather<-subset(weather,Mean.TemperatureF>=-99)